[package]
name = "random-file-server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
dotenv = "0.15"
html-escape = "0.2"
humansize = "2"
mime_guess = "2"
natord = "1"
rand = "0.9"
tiny_http = "0.12"
